---
deployment:
  tasks:
    - export DEPLOYPART=/home/u5587213/public_html/sisolusi.id/web/
    - /bin/cp index.html $DEPLOYPART
    - /bin/cp -R assets $DEPLOYPART
    - /bin/cp -R css $DEPLOYPART
    - /bin/cp -R js $DEPLOYPART
    - /bin/cp -R vendor $DEPLOYPART
